### ISSUE TITLE
Deploying Quiz: Phase 4 - Incorrect Question Format

### ISSUE THREAD

**Issue by Duke1014** [learn-co-curriculum/phase-4-quiz-deploying#1]
### Canvas Link

https://learning.flatironschool.com/courses/4689/quizzes/20986

### Concern

Question 3 asks to select all that apply, but it's currently impossible to select more than one option.

### Additional Context

![image](https://user-images.githubusercontent.com/67128440/144963580-a6d33602-9f1e-4eb7-8d1b-9c68cba32294.png)

**Comment by ihollander** [comment]
Hi @Duke1014 - thanks for flagging this issue! We'll update this question with the correct type to allow multiple answers.
