### ISSUE TITLE
Deploying Quiz: Phase 4

### ISSUE THREAD

**Issue by tloughrist** [learn-co-curriculum/phase-4-quiz-deploying#3]
### Canvas Link

https://learning.flatironschool.com/courses/5644/quizzes/34218

### Concern

Question 4 is marked incorrect when answer "Database Software" is selected. However, "Database Software" is the correct answer, as indicated by the feedback, i.e. "Right! It's generally a best practice to use the same database software locally as you use in production, since there are a few key differences between SQL database software (like SQLite and PostgreSQL)."

### Suggested Changes

Change which answer is marked as correct answer.

**Comment by jaguilar89** [comment]
Just had the same issue. Question 4 is marked incorrect with the correct response selected.

<img width="843" alt="Screen Shot 2023-01-09 at 6 02 52 PM" src="https://user-images.githubusercontent.com/78065152/211425893-1b2fd424-301d-44d0-af66-10b7bed9fd74.png">

**Comment by lizbur10** [comment]
Hi @tloughrist and @jaguilar89 ! Thanks for bringing this to our attention. The question should have allowed multiple selections, as both Database software and Ruby version are correct answers. This has now been fixed, though Canvas won't always update quizzes when students have already submitted responses, so it may not show up in your Canvas courses. It will be correct for students moving forward. Apologies for the inconvenience.

Thanks for contributing to the Flatiron School curriculum 💙
